# -*- coding: utf-8 -*-
"""registro datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQqIst5aNjifX6LcyMi0vQ7THUFfa6od
"""

def registro_datos():

 print ("Datos del Registro")

 dni = input("Ingrese DNI")
 while len(dni)!=8 or not dni.isdigit():
  print("dni incorrecto")
  dni=input("INGRESE DNI")

 usuario ={
   "dni" :dni,
   "nombre" :input("Ingrese nombre"),
   "apellido_paterno": input("Ingrese apellido paterno"),
   "apellido_materno" :input("ingrese apellido materno "),
   "edad" :int( input("Ingrese edad"))
}

 print(usuario["dni"], usuario["nombre"], usuario["apellido_paterno"], usuario["apellido_materno"])

 if usuario["edad"] >= 18:
    print("\n  usted accede a la convocatoria "  )
 else :
   print(" \n gracias pero no puede puede continuar")
 return usuario

usuarios =[]
for i in range(10):
    persona  =registro_datos()
    usuarios.append(persona)


print(" \n ====mostrar registro ")
for usuario in usuarios :
  print("*******************************")
  print ("DNI", usuario ["dni"])
  print ("NOMBRE",usuario["nombre"])
  print ("Apellido paterno ", usuario["apellido_paterno"])
  print("Apellido materno ", usuario["apellido_materno"])
  print("Edad", usuario["edad"])